### PR TITLE
Fix getPixelFromCoordinate function (close #23)

### LINKED ISSUE #23: A popup sometimes is NOT shown when clicking a marker
Hi @aarranz,

I encountered an error that a popup sometimes isn't shown when clicking a marker.

This condition to reproduce this issue is when scrolling a map across the international date line and clicking a marker.

- How to reproduce it
 
**NG:** Scroll the map to the right across the international date line and click a marker. A popup is NOT be shown.

png1

**OK:** Scroll the map to the left and click a marker. A popup is shown.

png2

- How to build an environment to reproduce it.
1. You do wiring the [Json injector](https://github.com/lets-fiware/json-injector/releases/download/v0.1.1/FISUDA_json-injector_0.1.1.wgt), NGSI Entity To PoI and OpenLayers Map v1.13 widget. 

png5

2. You set values in ol3 settings. Please set Initial Location to '135,34.7'.

png4

3. You send a following json data with Json injector.

png3

```
[
  {
    "id": "place001",
    "type": "PointOfInterest",
    "name": "San Francisco",
    "location": {
      "type": "Point",
      "coordinates": [-122.4194,37.7749]
    }
  }
] 
```
- Live demo
A live demo is the following link.
[https://mashup.lab.fisuda.jp/letsfiware/getpixelfromcoordinate#view=workspace&tab=%E3%82%BF%E3%83%96](https://mashup.lab.fisuda.jp/letsfiware/getpixelfromcoordinate#view=workspace&tab=%E3%82%BF%E3%83%96)

- Reference
It seems that this issue is that getPixelFromCoordinate function does not work properly.
[https://github.com/openlayers/openlayers/issues/4713](https://github.com/openlayers/openlayers/issues/4713)

### PR DESCRIPTION
**Pull request by fisuda**
Hi @aarranz,
It would be great if you could review this PR.
Thank you.

### CODE REVIEW

File: src/js/ol3-map-widget.js [hunk 1]
```diff
@@ -916,6 +916,9 @@
 
                 marker_coordinates = ol.extent.getCenter(feature.getGeometry().getExtent());
                 marker_position = this.map.getPixelFromCoordinate(marker_coordinates);
+                var view = this.map.getView();
```
Comment (aarranz) [inline src/js/ol3-map-widget.js]: Hi @fisuda.

Thank you very much for your contribution 😄. It LGTM although It'd be great if you can add a comment in this line providing the https://github.com/openlayers/openlayers/issues/4713 link as well as a new entry in the changelog.

Comment (fisuda) [reply src/js/ol3-map-widget.js]: Hi @aarranz,

I have just added a comment and updated changelog.md. Please have a look.

Thank you.

**Comment by aarranz** [comment]
Thank you very much! Merged :smiley:
